//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HALL()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.SEARCHes = new HashSet<SEARCH>();
        }
    
        public int HALLID { get; set; }
        public string HALLNAME { get; set; }
        public string HALLTYPE { get; set; }
        public decimal MINIMUMCOST { get; set; }
        public short MAXIMUMTABLE { get; set; }
        public string HALLIMAGE { get; set; }
        public string HALLDESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEARCH> SEARCHes { get; set; }
    }
}
