//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVE
    {
        public int SERVEID { get; set; }
        public int CUSTOMERID { get; set; }
        public int SERVICEID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
