//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int INVOICEID { get; set; }
        public decimal TOTALCOST { get; set; }
        public decimal SERVICECOST { get; set; }
        public decimal WEDDINGCOST { get; set; }
        public System.DateTime PAYDAY { get; set; }
        public string USERNAME { get; set; }
        public int WEDDINGID { get; set; }
        public decimal REMAININGCOST { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public Nullable<decimal> PENALTIES { get; set; }
        public Nullable<decimal> TABLECOST { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual REPORTDETAIL REPORTDETAIL { get; set; }
        public virtual WEDDING WEDDING { get; set; }
    }
}
