//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTDETAIL()
        {
            this.INVOICES = new HashSet<INVOICE>();
        }
    
        public System.DateTime REPORTDATE { get; set; }
        public Nullable<short> BOOKEDWEDDINGAMOUNT { get; set; }
        public Nullable<short> PAIDWEDDINGAMOUNT { get; set; }
        public Nullable<decimal> PROFIT { get; set; }
        public Nullable<double> RATIO { get; set; }
        public Nullable<System.DateTime> REPORTMONTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICES { get; set; }
        public virtual SALESREPORT SALESREPORT { get; set; }
    }
}
