//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVE
    {
        public int SERVEID { get; set; }
        public int WEDDINGID { get; set; }
        public int SERVICEID { get; set; }
        public Nullable<decimal> SERVICECOST { get; set; }
        public string NOTE { get; set; }
        public Nullable<byte> AMOUNT { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
        public virtual WEDDING WEDDING { get; set; }
    }
}
